#apiVersion: v1
#kind: Service
#metadata:
#  name: batch-visualizer-auth
#spec:
#  ports:
#    - name: "8080"
#      port: 8082
#      targetPort: 8080
#      nodePort: 30010
#  selector:
#    app: batch-visualizer-auth
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: batch-visualizer-auth
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
  selector:
    app: batch-visualizer-auth
  clusterIP: 10.107.154.20
  type: LoadBalancer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnvailable: 1
    type: RollingUpdate